# To get started with Dependabot version updates, you'll need to specify which
version: 2
updates:
  - package-ecosystem: 'npm' # See documentation for possible values
    directory: '/' # Location of package manifests
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 10